# Generated by Django 4.0.5 on 2022-07-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cleaner', models.CharField(choices=[('C', 'Cloth'), ('S', 'Silica'), ('A', 'Ammonia')], default='C', max_length=1)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gem')),
            ],
        ),
    ]
