# Generated by Django 4.0.6 on 2022-07-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_polishing_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polishing',
            options={'ordering': ['-date']},
        ),
    ]
